apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-transaction
  labels:
    app: service-transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-transaction
  template:
    metadata:
      labels:
        app: service-transaction
    spec:
      containers:
      - name: app-transaction
        image: holgadom/app-transaction:2
        ports:
        - containerPort: 5005
        env:
        - name: NACOS_PORT
          value: "8848"
        - name: NACOS_SERVERADDR
          value: "146.190.15.39"
        - name: NACOS_NAMESPACE
          value: "public"
        - name: NACOS_IDENTITYKEY
          value: "nacos"
        - name: NACOS_IDENTITYVALUE
          value: "nacos"
        - name: NACOS_DATAID
          value: "public"
        - name: NACOS_GROUP
          value: "DEFAULT_GROUP"
---
kind: Service
apiVersion: v1
metadata:
  name: app-transaction
spec:
  type: ClusterIP
  selector:
    app: service-transaction
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5005
    name: http